[package]
name = "rspotd-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
rspotd = "0.1.4"
rocket = "0.5.0-rc.1"
rocket_contrib = "0.4.10"
serde_json = "1.0.11"

[dependencies.rocket_dyn_templates]
features = ["tera"]
